# Flusim Web Interface Application
# Developed by Reilly Evans

# Imports
import time
import json
from pydantic import BaseModel, Field
from fastapi import FastAPI
from fastapi.responses import FileResponse

# Define structure of model configuration guide JSON files
class modelGuideFile(BaseModel):
    # TODO: flesh out with more parameters; hardcode anything the user won't change
    name: str = Field(
        title = 'Name', description = (
            'The name of the simulation guide file'
        )
    )
    description: str | None = Field(
        title = 'Description', description = (
            'A brief description of the simulations the guide file defines'
        )
    )
    output_folder: str = Field(
        title = 'Output Folder', default = './results/', description = (
            'The folder where the scenario database files will be output'
        )
    )
    middle_joint: str | None = Field(
        title = 'Middle Joint', default = '-interface', description = ((
            'A descriptive string that will be inserted into the names of the '
            'files generated by the simulations, between the community name '
            'and the version number'
        ))
    )
    community_used: list[str] = Field(
        title = 'Communities Used', default = ['newcastle'], description = ((
            'The communities to repeat all scenarios across, corresponding '
            'with the names of the communities configured in '
            'toolbox_config.json'
        ))
    )
    '''
    #shared_overrides: 
    override_templates: list[] | None = Field(
        title = 'Communities Used', default = None, description = ((
            'The communities to repeat all scenarios across, corresponding '
            'with the names of the communities configured in '
            'toolbox_config.json'
        ))
    )
    '''


'''
Sample Guide JSON COnfig Files



Minimal:
{
  "name": "Simple Test",
  "output_folder": "./results/",
  "middle_joint": "-coronaV",
  "community_used": [
    "newcastle"
  ],
  "community_overrides": [
    {
      "name": "newcastle",
      "parameters": {}
    }
  ],
  "shared_overrides": {
    "parameters": {
      "Command_Argument": {
        "n_runs": 24,
        "n_cycles": 720
      },
      "Scenario_Strain": [
        {
          "StrainId": 0,
          "Beta": 0.11
        }
      ]
    }
  },
  "override_templates": [
    {
      "name": "test_1",
      "parameters": {
        "Scenario_Parameter": {
          "seed_rate": 0.125,
          "school_closure_trigger": "timed",
          "school_closure_compliance": 0.5,
          "school_closure_delay": 28,
          "withdrawal_increase_trigger": "timed",
          "withdrawal_increase_delay": 28,
          "work_nonattendance_trigger": "timed",
          "prob_work_nonattendance": 0.5,
          "work_nonattendance_delay": 28
        }
      }
    }
  ],
  "simulation_sets": [
    {
      "name": "test_set_1",
      "version": 230,
      "simulations": [
        {
          "name": "test_sim_1",
          "apply_template": [
            "test_1"
          ]
        },
        {
          "name": "test_sim_2",
          "apply_template": [
            "test_1"
          ]
        }
      ]
    }
  ]
}



SSG:
{
  "name": "Sample simulation guide",
  "description": "A simple simulation guide that shows how the simulation runner works",
  "output_folder": "./results/",
  "middle_joint": "-coronaV",
  "community_used": [
    "newcastle"
  ],
  "override_templates": [
    {
      "name": "Perth interventions",
      "description": "SC50+ICI+WN50+CCR80 delays 2 weeks, then have multi-phase school closure setting.",
      "notes": "When use intervention manipulation, remember to change numbers to 3 and onwards",
      "parameters": {
        "Scenario_Parameter": {
          "seed_rate": 0.125,
          "school_closure_trigger": "timed",
          "school_closure_compliance": 0.5,
          "school_closure_delay": 28,
          "withdrawal_increase_trigger": "timed",
          "withdrawal_increase_delay": 28,
          "work_nonattendance_trigger": "timed",
          "prob_work_nonattendance": 0.5,
          "work_nonattendance_delay": 28,
          "bcc_reduction_trigger": "timed",
          "bcc_reduction": 0.2,
          "bcc_reduction_delay": 28
        },
        "Scenario_DynamicIntervention": [
          {
            "Name": "school_closure",
            "CycleOffset": 78,
            "NewValue": 1
          },
          {
            "Name": "school_closure",
            "CycleOffset": 116,
            "NewValue": 0.75
          },
          {
            "Name": "school_closure",
            "CycleOffset": 144,
            "NewValue": 0.55
          }
        ]
      }
    }
  ],
  "community_overrides": [
    {
      "name": "newcastle",
      "parameters": {
        "Scenario_ParameterWithAgePrefix": {
          "strain_0_initial_natural_immunity": 0
        }
      }
    }
  ],
  "shared_overrides": {
    "parameters": {
      "Command_Argument": {
        "n_runs": 24,
        "n_cycles": 720
      },
      "Scenario_Strain": [
        {
          "StrainId": 0,
          "Beta": 0.11
        }
      ],
      "Scenario_Parameter": {
        "vaccination_trigger": "timed"
      }
    }
  },
  "simulation_sets": [
    {
      "name": "Surge test on SC50+WN50+CCR80 2 weeks delay",
      "version": 96,
      "simulations": [
        {
          "name": "no surge",
          "apply_template": [
            "Perth interventions"
          ]
        },
        {
          "name": "surged",
          "apply_template": [
            "Perth interventions"
          ],
          "override_setting": {
            "parameters": {
              "Scenario_DynamicIntervention": [
                {
                  "Name": "seed_rate",
                  "CycleOffset": 184,
                  "NewValue": 2.5
                },
                {
                  "Name": "seed_rate",
                  "CycleOffset": 186,
                  "NewValue": 0.125
                }
              ]
            }
          }
        }
      ]
    }
  ]
}



Beta Increase:
{
    "name": "Sample simulation guide",
    "description": "A simple simulation guide that shows how the simulation runner works",
    "output_folder": "./results/",
    "middle_joint": "-coronaV",
    "community_used": ["newcastle"],
    "override_templates": [
        {
            "name": "Perth interventions",
            "description": "SC50+ICI+WN50+CCR80 delays 2 weeks, then have multi-phase school closure setting.",
            "notes": "When use intervention manipulation, remember to change numbers to 3 and onwards",
            "Scenario_Parameter": {
                "seed_rate": 0.125,
                "school_closure_trigger": "timed",
                "school_closure_compliance": 0.5,
                "school_closure_delay": 28,
                "withdrawal_increase_trigger": "timed",
                "withdrawal_increase_delay": 28,
                "work_nonattendance_trigger": "timed",
                "prob_work_nonattendance": 0.5,
                "work_nonattendance_delay": 28,
                "bcc_reduction_trigger": "timed",
                "bcc_reduction": 0.2,
                "bcc_reduction_delay": 28
            },
            "Scenario_DynamicIntervention": [
                {
                    "Name": "school_closure",
                    "CycleOffset": 78,
                    "NewValue": 1.0
                },
                {
                    "Name": "school_closure",
                    "CycleOffset": 116,
                    "NewValue": 0.75
                },
                {
                    "Name": "school_closure",
                    "CycleOffset": 144,
                    "NewValue": 0.55
                }
            ]
        }
    ],
    "community_overrides": [
        {
            "name": "newcastle",
            "Scenario_ParameterWithAgePrefix": {
                "strain_0_initial_natural_immunity": 0.0
            }
        }
    ],
    "shared_overrides": {
        "Command_Argument": {
            "n_runs": 24,
            "n_cycles": 720
        },
        "Scenario_Parameter": {
            "vaccination_trigger": "timed"
        }
    },
    "simulation_sets": [
        {
            "name": "Surge test on SC50+WN50+CCR80 2 weeks delay",
            "version": 231,
            "simulations": [
                {
                    "name": "beta normal",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.11
                            }
                        ]
                    }
                },
                {
                    "name": "beta increase 1",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.12
                            }
                        ]
                    }
                },
                {
                    "name": "beta increase 2",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.13
                            }
                        ]
                    }
                },
                {
                    "name": "beta increase 3",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.14
                            }
                        ]
                    }
                },
                {
                    "name": "beta increase 4",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.15
                            }
                        ]
                    }
                },
                {
                    "name": "beta increase 5",
                    "apply_template": ["Perth interventions"],
                    "override_setting": {
                        "Scenario_Strain": [
                            {
                                "StrainId": 0,
                                "Beta": 0.16
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
'''



flusimApp = FastAPI()

#TODO: Add CORS middleware if necessary

# Define route for receiving model parameters
@flusimApp.post('/runModel', response_class = FileResponse)
async def runModel():
    requestedData = json.loads()
    print(f'Simulation received; name = {requestedData["name"]}')
    # TODO: run flusim simulation
    time.sleep(3) # Simulate long running time
    # For now this'll just send over the existing CSV file
    return FileResponse('./newcastle-coronaV96-epidemic-mean.csv')
