[global]

disableWidgetStateDuplicationWarning = true

[runner]

magicEnabled = false

[server]

enableStaticServing = true

[browser]

gatherUsageStats = false

[theme]

# TODO: This breaks light/dark mode; see if that can be fixed
baseFontSize = 22